---
title: <center>Publikace, prezentace a postery</center>
---

## 2020  
* Slabá, J. 2020. **Nezaměstnanost ženy jako příčina deklarovaného odkladu založení rodiny?**. Sociológia, 52(2), s. 132–152. ISSN 0049-1225. IF 0.471. [článek](https://doi.org/10.31577/sociologia.2020.52.2.6.)
* **The relationship of fertility decline and individualization**, konference Young Demographers, Praha, únor 2020, [poster](postersandpresentations/2020_02_YD.pdf)
* **Neobyčejná demografie obyčejného života**, propagační přednáška v rámci Dne otevřených dvěří, Praha, leden 2020, [prezentace](postersandpresentations/2020_01_DOD.pdf)

## 2019  
* Altová A., Maláková, K., Slabá, J. 2019. **Nejvýznamnější proměny v reprodukčním chování světové populace**. Geografické rozhledy, 29(1), 26–29. [článek](https://www.geograficke-rozhledy.cz/archiv/clanek/2900)
* Šťastná A., Slabá, J., Kocourková J. 2019. **Druhé dítě – neplánovaný odklad a časování jeho narození**. Demografie, 61, p. 77–92. [článek](https://www.czso.cz/documents/10180/91917740/13005319q2_77.pdf/b0972342-7094-4feb-bf85-f0acb04e1f30?version=1.0)
* **Czech fertility postponement at the turn of the millennium**, LabTalk MPIDR, Rostock, listopad 2019, [prezentace](postersandpresentations/2019_11_MPIDR.pdf)
* **The Effect of Unemployment Experience to First Birth Fertility**, konference ESA, Manchester, srpen 2019, [prezentace](postersandpresentations/2019_08_ESA.pdf)
* **Odklad plodnosti v Česku na přelomu tisíciletí**, obhajoba minima disertační práce v rámci státní závěrečné zkoušky, Praha, červen 2019, [prezentace](postersandpresentations/2019_06_ObhajobaMinimum.pdf)
* **The effect of unemployment experience on fertility timing**, konference PopFest, Londýn, květen 2019, [prezentace](postersandpresentations/2019_05_PF.pdf)
* **The Effect of Unemployment Experience to the First Birth Fertility, Czechia in the 21st Century**, konference Young Demographers, Praha, únor 2019, [prezentace](postersandpresentations/2019_02_YD.pdf)

## 2018
* **Opinions, Plans and the Timing of Fertility, Differences among Czech Women Generations 1966–1990**, konference RELIK, Praha, listopad 2018, [prezentace](postersandpresentations/2018_11_RELIK.pdf)
* **Unplanned Postponement of First and Second Births in the Czech Republic**, konference EPC, Brusel, červen 2018, [poster](postersandpresentations/2018_06_EPC.pdf)
* **Neplánovaný odklad reprodukčních plánů prvního a druhého pořadí v České republice**, konference ČDS, Brno, květen 2018, [poster](postersandpresentations/2018_05_CDS.pdf)

## 2017  
* Šťastná A., Slabá, J. Kocourková J. 2017. **Plánování, načasování a důvody odkladu narození prvního dítěte v České republice**. Demografie. 59, 207–223, [článek](https://www.czso.cz/documents/10180/46203816/stastna.pdf/0cf15559-1e0a-4b47-a7d6-e8faeb236404?version=1.0)
* **Causes of Fertility Postponement in the Czech Republic for Birth Cohorts from 1966 to 1990**, konference Young Demographers, Praha, únor 2017, [poster](postersandpresentations/2017_02_YD.pdf)

## 2016
* Hulíková, K., Slabá, J., 2016. **Hispánci jako nedílná součást Spojených států amerických**. Geografické rozhledy, 25(4), s. 20–21. [článek](https://www.geograficke-rozhledy.cz/archiv/clanek/115/pdf)
* **Využití času v závislosti na přítomnosti dítěte v domácnosti v generacích 40. až 70. let 20. století ve Spojených státech amerických**, prezentace tématu diplomové práce v rámci semináře pro magisterské stuednty, Praha, říjen 2016, [poster](postersandpresentations/2016_10_SEMINAR.pdf)

## 2015
* Kociánová, G., Moszová, V., Růžičková, M., Slabá, J., Vrabcová, M. and O. Kurtinová, 2015. **Přehled publikovaných příspěvků v časopise Demografie, revue pro výzkum populačního vývoje k vybraným problematikám teoretické demografie**. Demografie, 57(3), pp. 283-293. [článek](https://www.czso.cz/documents/10180/20555393/13005315q3.pdf/05492ae5-7188-4275-8372-c83b23f9821f?version=1.1)
* Kociánová, G., Moszová, V., Papřoková, P., Slabá, J., Tvrz, M. and B. Burcin. 2015. **Internet Resources for Population Studies**. Available at official website of department of Demography and Geodemography [online zdroj](https://www.natur.cuni.cz/geography/department-of-demography-and-geodemography/internet-resources-for-population-studies)




